  version: '3.8'
  services:
    dynamodb-local:
      command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
      image: "amazon/dynamodb-local:latest"
      container_name: dynamodb-local
      ports:
        - "8000:8000"
      volumes:
        - "./docker/dynamodb:/home/dynamodblocal/data"
      working_dir: /home/dynamodblocal
      networks:
        - hexafood-bridge
        
    api-producao:
      container_name: 'hexafood-api-producao'
      build:
        context: .
        dockerfile: Dockerfile
        args:
          - NODE_ENV=development
      env_file:
        - .env
      environment:
        AWS_ACCESS_KEY_ID: 'DUMMYIDEXAMPLE'
        AWS_SECRET_ACCESS_KEY: 'DUMMYEXAMPLEKEY'
        REGION: 'eu-west-1'

      ports:
        - 3000:3000
      depends_on:
        - "dynamodb-local"
      links:
        - "dynamodb-local"
      command: ["./wait-for-it.sh", "dynamodb:8000", "--", "./start.sh"]
      volumes:
        - .:/home/node/app
        - /home/node/app/node_modules  
  
    localstack:
      image: localstack/localstack:latest
      ports:
        - '4566-4597:4566-4597'
      environment:
        - AWS_ACCESS_KEY_ID=dummy
        - AWS_SECRET_ACCESS_KEY=dummy
        - AWS_DEFAULT_REGION=us-east-1
        - DEBUG=1
        - LOCALSTACK_PERSISTENCE=1
        - SERVICES=sqs
        - DEFAULT_REGION=us-east-1
        - EDGE_PORT=4566
        - SQS_ENDPOINT_STRATEGY=path
        - HOSTNAME_EXTERNAL=localstack
      volumes:
        - "./docker-compose/localstack:/var/lib/localstack"
      networks:
        - hexafood-bridge


  networks:
    hexafood-bridge:
      driver: bridge
