  version: '3.8'
  services:
    mongo:
      container_name: mongo-hexafood
      image: mongo
      ports:
        - "27017:27017"
      networks:
        - hexafood-bridge
      volumes:
        - ./data:/data/db
        - ./init-mongo.js:/docker-entrypoint-initdb.d/init.js:ro
      environment:
        - MONGO_INITDB_ROOT_USERNAME=mongouser
        - MONGO_INITDB_ROOT_PASSWORD=mongopassword
        - MONGO_INITDB_DATABASE=mydatabase
      restart: on-failure
    api-producao:
      container_name: 'hexafood-api-producao'
      build:
        context: .
        dockerfile: Dockerfile
        args:
          - NODE_ENV=development
      env_file:
        - .env.dev
      environment:
        - MONGO_URI=mongodb://mongo:27017/MONGODB_URL
      networks:
        - hexafood-bridge
      ports:
        - 3000:3000
      depends_on:
        - mongo
      command: ["./wait-for-it.sh", "mongo:27017", "--", "./start.sh"]
      volumes:
        - .:/home/node/app
        - /home/node/app/node_modules  
      links:
        - mongo  

  networks:
    hexafood-bridge:
      driver: bridge

  volumes:
    dbdata: