  version: '3.8'
  services:
    mongo:
      image: mongo
      ports:
        - "27017:27017"
      networks:
      - hexafood-bridge
      volumes:
        - dbdata:/data/db
      healthcheck:
        test: ["CMD", "mongo", "--eval", "db.adminCommand('Mongo is working!')"]
        interval: 10s
        timeout: 5s
        retries: 5

    api:
      container_name: 'hexafood-api'
      build:
        context: .
        dockerfile: Dockerfile
        args:
          - NODE_ENV=development
      env_file:
        - .env.dev
      environment:
        - MONGO_URI=mongodb://mongo:27017/MONGODB_URL
      networks:
        - hexafood-bridge
      ports:
        - 3000:3000
      depends_on:
        - mongo
      command: ["./wait-for-it.sh", "mongo:27017", "--", "./start.sh"]
      volumes:
        - .:/home/node/app
        - /home/node/app/node_modules    

  networks:
    hexafood-bridge:
      driver: bridge

  volumes:
    dbdata: