  version: '3.8'
  services:    
    api-producao:
      container_name: 'hexafood-api-producao'
      build:
        context: .
        dockerfile: Dockerfile
        args:
          - NODE_ENV=development
      env_file:
        - .env.dev
      ports:
        - 3000:3000
      depends_on:
        - localstack
      command: ["./wait-for-it.sh", "localstack:4566", "--", "./start.sh"]
      volumes:
        - .:/home/node/app
        - /home/node/app/node_modules 
      networks:
        - hexafood-bridge 
  
    localstack:
      image: localstack/localstack:latest
      ports:
        - '4566-4597:4566-4597'
      environment:
        - AWS_ACCESS_KEY_ID=dummy
        - AWS_SECRET_ACCESS_KEY=dummy
        - AWS_DEFAULT_REGION=us-east-1
        - DEBUG=1
        - LOCALSTACK_PERSISTENCE=1
        - SERVICES=sqs,dynamodb
        - DEFAULT_REGION=us-east-1
        - EDGE_PORT=4566
        - SQS_ENDPOINT_STRATEGY=path
        - HOSTNAME_EXTERNAL=localstack
      volumes:
        - "./docker-compose/localstack:/var/lib/localstack"
        - ./docker-compose/start-localstack.sh:/etc/localstack/init/ready.d/start-localstack.sh
      networks:
        - hexafood-bridge

  networks:
    hexafood-bridge:
      driver: bridge
