apiVersion: apps/v1
kind: Deployment
metadata:
  name: dynamodb-deployment
  labels:
    app: dynamodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dynamodb
  template:
    metadata:
      labels:
        app: dynamodb
    spec:
      containers:
        - name: dynamodb
          image: amazon/dynamodb-local
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: dynamodb-service
spec:
  selector:
    app: dynamodb
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
