name: Node.js CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.13.x'

    - name: Install dependencies
      run: yarn

    - name: Test 
      run: yarn test --coverage

    - name: Publish Coverage
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: coverage/lcov.info

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_PROJECT_KEY: brpadilha_hexafood-producao
        SONAR_ORGANIZATION: brpadilha

    - name: Build
      run: yarn build

    - name: docker login
      uses: docker/login-action@v2
      with: 
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build the Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: brpadilha/hexafood:latest
